/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function proxyCheckHttp(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function proxyCheckSocks5(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function loggerInit(): void
