/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DownloadProgress {
  target: string
  downloaded: number
  total?: number | undefined | null
}
export interface HttpFileDownloaderResponse {
  status: boolean
  ecode: number
  message: string
}
export function proxyCheckHttp(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function proxyCheckSocks5H(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function proxyCheckSocks5(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export interface LoginData {
  username: string
  password: string
}
export interface LoginCreationParams {
  username: string
  password: string
  url: string
  usernameField: string
  passwordField: string
}
export function sqliteAddLoginPassword(filepath: string, loginParams: LoginCreationParams): Promise<LoginData>
export function createSqliteLoginDatabase(path: string): Promise<boolean>
export function archivateFolder(outputFile: string, inputDir: string, fileList: Array<string>): Promise<boolean>
export function killProcessByPid(pid: number): number
export function setForegroundByPid(pid: number): number
export function rustLoggerInit(): void
export class HttpFileDownloader {
  constructor(emitter?: (...args: any[]) => any | undefined | null)
  downloadFile(url: string, file: string): Promise<HttpFileDownloaderResponse>
}
