/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DownloadProgress {
  target: string
  downloaded: number
  total?: number | undefined | null
}
export interface HttpFileDownloaderResponse {
  status: boolean
  ecode: number
  message: string
}
export function proxyCheckHttp(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function proxyCheckSocks5H(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function proxyCheckSocks5(ip: string, port: number, username?: string | undefined | null, password?: string | undefined | null): Promise<string>
export function archivateFolder(outputFile: string, inputDir: string, fileList: Array<string>): Promise<boolean>
export function setForegroundByPid(pid: number): boolean
export function killProcessByPid(pid: number): number
export function rustLoggerInit(): void
export class HttpFileDownloader {
  constructor(emitter?: (...args: any[]) => any | undefined | null)
  downloadFile(url: string, filename: string): Promise<HttpFileDownloaderResponse>
}
