[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "codegen-units=1", "-C", "lto=false"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]